
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.BranchScalarFieldEnum = {
  id: 'id',
  code: 'code',
  name: 'name',
  nameAr: 'nameAr',
  address: 'address',
  addressAr: 'addressAr',
  phone: 'phone',
  hours: 'hours',
  city: 'city',
  isActive: 'isActive',
  createdAt: 'createdAt',
  dailyCode: 'dailyCode',
  dailyCodeExpiresAt: 'dailyCodeExpiresAt'
};

exports.Prisma.CustomerScalarFieldEnum = {
  id: 'id',
  mobile: 'mobile',
  name: 'name',
  email: 'email',
  birthday: 'birthday',
  language: 'language',
  isBlocked: 'isBlocked',
  homeBranchId: 'homeBranchId',
  pointsBalance: 'pointsBalance',
  visitCount: 'visitCount',
  totalSpend: 'totalSpend',
  lastVisitAt: 'lastVisitAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OtpCodeScalarFieldEnum = {
  id: 'id',
  mobile: 'mobile',
  codeHash: 'codeHash',
  purpose: 'purpose',
  attempts: 'attempts',
  expiresAt: 'expiresAt',
  consumedAt: 'consumedAt',
  createdAt: 'createdAt',
  pendingName: 'pendingName',
  pendingEmail: 'pendingEmail',
  pendingBirthday: 'pendingBirthday',
  pendingBranchId: 'pendingBranchId'
};

exports.Prisma.QrTokenScalarFieldEnum = {
  id: 'id',
  token: 'token',
  customerId: 'customerId',
  expiresAt: 'expiresAt',
  usedAt: 'usedAt',
  createdAt: 'createdAt'
};

exports.Prisma.StaffScalarFieldEnum = {
  id: 'id',
  username: 'username',
  name: 'name',
  pinHash: 'pinHash',
  role: 'role',
  isActive: 'isActive',
  branchId: 'branchId',
  createdAt: 'createdAt',
  lastLogin: 'lastLogin'
};

exports.Prisma.TransactionScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  branchId: 'branchId',
  staffId: 'staffId',
  invoiceNumber: 'invoiceNumber',
  amount: 'amount',
  pointsEarned: 'pointsEarned',
  discountGiven: 'discountGiven',
  isReversed: 'isReversed',
  reversedAt: 'reversedAt',
  reverseReason: 'reverseReason',
  createdAt: 'createdAt'
};

exports.Prisma.PointsLedgerScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  transactionId: 'transactionId',
  delta: 'delta',
  reason: 'reason',
  note: 'note',
  createdAt: 'createdAt',
  expiresAt: 'expiresAt'
};

exports.Prisma.RewardScalarFieldEnum = {
  id: 'id',
  name: 'name',
  nameAr: 'nameAr',
  description: 'description',
  descriptionAr: 'descriptionAr',
  type: 'type',
  threshold: 'threshold',
  value: 'value',
  isPercent: 'isPercent',
  validDays: 'validDays',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.CustomerRewardScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  rewardId: 'rewardId',
  status: 'status',
  issuedAt: 'issuedAt',
  expiresAt: 'expiresAt',
  redeemedAt: 'redeemedAt',
  redeemedTxId: 'redeemedTxId'
};

exports.Prisma.OfferScalarFieldEnum = {
  id: 'id',
  name: 'name',
  nameAr: 'nameAr',
  description: 'description',
  descriptionAr: 'descriptionAr',
  discountValue: 'discountValue',
  isPercent: 'isPercent',
  segment: 'segment',
  startsAt: 'startsAt',
  endsAt: 'endsAt',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.OfferBranchScalarFieldEnum = {
  offerId: 'offerId',
  branchId: 'branchId'
};

exports.Prisma.AuditLogScalarFieldEnum = {
  id: 'id',
  staffId: 'staffId',
  action: 'action',
  entityType: 'entityType',
  entityId: 'entityId',
  reason: 'reason',
  metadata: 'metadata',
  createdAt: 'createdAt'
};

exports.Prisma.SettingScalarFieldEnum = {
  key: 'key',
  value: 'value',
  updatedAt: 'updatedAt'
};

exports.Prisma.CustomerVisitScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  branchId: 'branchId',
  couponCode: 'couponCode',
  pointsEarned: 'pointsEarned',
  checkInMethod: 'checkInMethod',
  note: 'note',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.Role = exports.$Enums.Role = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  COMPANY_ADMIN: 'COMPANY_ADMIN',
  BRANCH_MANAGER: 'BRANCH_MANAGER',
  CASHIER: 'CASHIER'
};

exports.RewardType = exports.$Enums.RewardType = {
  WELCOME: 'WELCOME',
  POINTS: 'POINTS',
  VISITS: 'VISITS',
  BIRTHDAY: 'BIRTHDAY',
  REFERRAL: 'REFERRAL',
  MANUAL: 'MANUAL'
};

exports.RewardStatus = exports.$Enums.RewardStatus = {
  AVAILABLE: 'AVAILABLE',
  REDEEMED: 'REDEEMED',
  EXPIRED: 'EXPIRED'
};

exports.Prisma.ModelName = {
  Branch: 'Branch',
  Customer: 'Customer',
  OtpCode: 'OtpCode',
  QrToken: 'QrToken',
  Staff: 'Staff',
  Transaction: 'Transaction',
  PointsLedger: 'PointsLedger',
  Reward: 'Reward',
  CustomerReward: 'CustomerReward',
  Offer: 'Offer',
  OfferBranch: 'OfferBranch',
  AuditLog: 'AuditLog',
  Setting: 'Setting',
  CustomerVisit: 'CustomerVisit'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
